import { Component } from '@angular/core';
import { QuitModel } from '../../../Model/quit.model';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'list',
  imports: [MatIconModule,RouterLink],
  templateUrl: './list.component.html',
  styleUrl: './list.component.css'
})
export class ListQuittanceComponent {
quittances: QuitModel[] = [
  {
    Numero: 5001,
    Numbor: 1001,
    Lignebor: 1,
    Idente: 'Q5001',
    Contrat: 3001,
    Police: 'POL-0001',
    Nature: 'C',
    Entite: 1,
    Cie: 101,
    Confie: false,
    Gestion: 'AUTO',
    Bloque: false,
    Affecte: true,
    Emission: 1,
    Encaiss: 1,
    Enreg: new Date(),
    Sitcli: 'EMISE',
    Dsitcli: new Date(),
    Sitcie: 'AFFECTEE',
    Retcie: 'OK',
    Dsitcie: new Date(),
    Numcie: 'NC-0001',
    Debeffet: new Date('2025-07-01'),
    Fineffet: new Date('2026-07-01'),
    Debit: new Date('2025-07-05'),
    Soldedu: 15000,
    Soldedu1: 'DJF',
    Totquit: 20000,
    Totquit1: 'DJF',
    Ptotale: 21000,
    Ptotale1: 'DJF',
    Pnette: 18000,
    Pnette1: 'DJF',
    Comm: 3000,
    Comm1: 'DJF',
    Taxe: 500,
    Taxe1: 'DJF',
    Libelle: 'Quittance Auto',
    Echprin: false,
  },
  {
    Numero: 5002,
    Numbor: 1002,
    Lignebor: 1,
    Idente: 'Q5002',
    Contrat: 3002,
    Police: 'POL-0002',
    Nature: 'R',
    Entite: 2,
    Cie: 102,
    Confie: true,
    Gestion: 'SANTE',
    Bloque: false,
    Affecte: false,
    Emission: 2,
    Encaiss: 2,
    Enreg: new Date(),
    Sitcli: 'ENCOURS',
    Dsitcli: new Date(),
    Sitcie: 'ENCOURS',
    Retcie: 'ENATTENTE',
    Dsitcie: new Date(),
    Numcie: 'NC-0002',
    Debeffet: new Date('2025-07-10'),
    Fineffet: new Date('2026-07-10'),
    Debit: new Date('2025-07-15'),
    Soldedu: 8000,
    Soldedu1: 'DJF',
    Totquit: 12000,
    Totquit1: 'DJF',
    Ptotale: 12500,
    Ptotale1: 'DJF',
    Pnette: 11000,
    Pnette1: 'DJF',
    Comm: 1000,
    Comm1: 'DJF',
    Taxe: 500,
    Taxe1: 'DJF',
    Libelle: 'Quittance Santé',
    Echprin: true,
  },
  ...Array.from({ length: 8 }, (_, i) => ({
    Numero: 5003 + i,
    Numbor: 1003 + i,
    Lignebor: i + 1,
    Idente: `Q500${i + 3}`,
    Contrat: 3003 + i,
    Police: `POL-000${i + 3}`,
    Nature: i % 2 === 0 ? 'C' : 'R',
    Entite: (i % 3) + 1,
    Cie: 103 + i,
    Confie: i % 2 === 0,
    Gestion: 'GEN',
    Bloque: false,
    Affecte: i % 2 === 0,
    Emission: 1,
    Encaiss: 2,
    Enreg: new Date(),
    Sitcli: 'ENCOURS',
    Dsitcli: new Date(),
    Sitcie: 'ENCOURS',
    Retcie: 'ENATTENTE',
    Dsitcie: new Date(),
    Numcie: `NC-000${i + 3}`,
    Debeffet: new Date(`2025-07-${10 + i}`),
    Fineffet: new Date(`2026-07-${10 + i}`),
    Debit: new Date(`2025-07-${12 + i}`),
    Soldedu: 5000 + i * 1000,
    Soldedu1: 'DJF',
    Totquit: 8000 + i * 1000,
    Totquit1: 'DJF',
    Ptotale: 8500 + i * 1000,
    Ptotale1: 'DJF',
    Pnette: 7500 + i * 1000,
    Pnette1: 'DJF',
    Comm: 1000 + i * 200,
    Comm1: 'DJF',
    Taxe: 500,
    Taxe1: 'DJF',
    Libelle: `Quittance ${i + 3}`,
    Echprin: i % 2 === 0,
  })),
];



  encaisser(){

    alert(
      'Quittance encaissé avec succés'
    )
  }
}
