export interface Produit {
    codeprod: string;
    branche?: string;
    branc?: string;
    libelle?: string;
    cieprin?: any;
    listeext?: string;
    pronopol?: string;
    pronoave?: string;
    groupe?: any;
    tartype?: string;
    tardev?: string;
    tarcle?: string;
    tararro?: any;
    taxatt?: number;
    taxatt1?: string;
    ftaxatt?: string;
    sceretro?: string;
    tauxatt?: any;
    modgarc?: string;
    modgarr?: string;
    tauxano?: number;
    formcomm?: string;
    extobli?: string;
    paniers?: string;
    nondispo?: any;
    majcrm?: string;
    tarmaj?: string;
    modegest?: string;
    ctrlgar?: string;
    catalog?: string;
    ole?: string;
    typarro?: string;
    fvahom?: any;
  }
  export const produitFieldMap: Record<keyof Produit, string> = {
    codeprod: 'b_codeprod',
    branche: 'b_branche',
    branc: 'b_branc',
    libelle: 'b_libelle',
    cieprin: 'b_cieprin',
    listeext: 'b_listeext',
    pronopol: 'b_pronopol',
    pronoave: 'b_pronoave',
    groupe: 'b_groupe',
    tartype: 'b_tartype',
    tardev: 'b_tardev',
    tarcle: 'b_tarcle',
    tararro: 'b_tararro',
    taxatt: 'b_taxatt',
    taxatt1: 'b_taxatt1',
    ftaxatt: 'b_ftaxatt',
    sceretro: 'b_sceretro',
    tauxatt: 'b_tauxatt',
    modgarc: 'b_modgarc',
    modgarr: 'b_modgarr',
    tauxano: 'b_tauxano',
    formcomm: 'b_formcomm',
    extobli: 'b_extobli',
    paniers: 'b_paniers',
    nondispo: 'b_nondispo',
    majcrm: 'b_majcrm',
    tarmaj: 'b_tarmaj',
    modegest: 'b_modegest',
    ctrlgar: 'b_ctrlgar',
    catalog: 'b_catalog',
    ole: 'b_ole',
    typarro: 'b_typarro',
    fvahom: 'b_fvahom',
  };

 export const produitTagMap: Record<keyof Produit, string> = {
    codeprod: 'b_codeprod',
    branche: 'b_branche',
    branc: 'b_branc',
    libelle: 'b_libelle',
    cieprin: 'b_cieprin',
    listeext: 'b_listeext',
    pronopol: 'b_pronopol',
    pronoave: 'b_pronoave',
    groupe: 'b_groupe',
    tartype: 'b_tartype',
    tardev: 'b_tardev',
    tarcle: 'b_tarcle',
    tararro: 'b_tararro',
    taxatt: 'b_taxatt',
    taxatt1: 'b_taxatt1',
    ftaxatt: 'b_ftaxatt',
    sceretro: 'b_sceretro',
    tauxatt: 'b_tauxatt',
    modgarc: 'b_modgarc',
    modgarr: 'b_modgarr',
    tauxano: 'b_tauxano',
    formcomm: 'b_formcomm',
    extobli: 'b_extobli',
    paniers: 'b_paniers',
    nondispo: 'b_nondispo',
    majcrm: 'b_majcrm',
    tarmaj: 'b_tarmaj',
    modegest: 'b_modegest',
    ctrlgar: 'b_ctrlgar',
    catalog: 'b_catalog',
    ole: 'b_ole',
    typarro: 'b_typarro',
    fvahom: 'b_fvahom'
  };