// export interface QuitModel {
//     numero: number;
//     numbor?: number;
//     lignebor?: number;
//     idente?: string;
//     contrat?: number;
//     piece?: number;
//     police?: string;
//     nature?: QitNature;
//     entite?: number;
//     cie?: number;
//     confie?: boolean;
//     gestion?: QitGestion;
//     quitopt?: boolean;
//     bloque?: boolean;
//     affecte?: boolean;
//     emission?: number;
//     encaiss?: number;
//     enreg?: Date;
//     sitcli?: QitSitCli;
//     typeff?: string;
//     dsitcli?: Date;
//     sitcie?: QitSitCie;
//     retcie?: QitRetour;
//     dsitcie?: Date;
//     numcie?: string;
//     debeffet?: Date;
//     fineffet?: Date;
//     debit?: Date;
//     rcm?: number;
//     indice?: number;
//     coeff?: string;
//     soldedu?: number;
//     soldedu1?: string;
//     totquit?: number;
//     totquit1?: string;
//     ptotale?: number;
//     ptotale1?: string;
//     pnette?: number;
//     pnette1?: string;
//     ppure?: number;
//     ppure1?: string;
//     catnat?: number;
//     catnat1?: string;
//     ristec?: number;
//     ristec1?: string;
//     frcie?: number;
//     frcie1?: string;
//     comm?: number;
//     comm1?: string;
//     commges?: number;
//     commges1?: string;
//     taxe?: number;
//     taxe1?: string;
//     taxatt?: number;
//     taxatt1?: string;
//     frgest?: number;
//     frgest1?: string;
//     netcie?: number;
//     netcie1?: string;
//     acompte?: number;
//     acompte1?: string;
//     hono?: number;
//     hono1?: string;
//     code_tva?: string;
//     taux_tva?: number;
//     tvafr?: number;
//     tvafr1?: string;
//     frprel?: number;
//     frprel1?: string;
//     frcbt?: number;
//     frcbt1?: string;
//     memo?: string;
//     prorata?: number;
//     Numtiers?: number;
//     prelevok?: boolean;
//     datenc?: Date;
//     commatt?: number;
//     commatt1?: string;
//     ecart?: number;
//     ecart1?: string;
//     histo?: string;
//     coeffenc?: number;
//     libelle?: string;
//     adhesion?: number;
//     tvaht?: number;
//     tvaht1?: string;
//     tvamnt?: number;
//     tvamnt1?: string;
//     nfacture?: string;
//     basetra?: number;
//     basetra1?: string;
//     basetrb?: number;
//     basetrb1?: string;
//     basetrc?: number;
//     basetrc1?: string;
//     txtra?: number;
//     txtrb?: number;
//     txtrc?: number;
//     txdna?: number;
//     mandat?: number;
//     dispatch?: boolean;
//     quitlie?: number;
//     echprin?: boolean;
//     ext?: string;
//   }
export interface QuitModel {
  Numero: number;
  Numbor?: number;
  Lignebor?: number;
  Idente?: string;
  Contrat?: number;
  Piece?: number;
  Police?: string;
  Nature?: string;
  Entite?: number;
  Cie?: number;
  Confie?: boolean;
  Gestion?: string;
  Quitopt?: boolean;
  Bloque?: boolean;
  Affecte?: boolean;
  Emission?: number;
  Encaiss?: number;
  Enreg?: Date;
  Sitcli?: string;
  Typeff?: string;
  Dsitcli?: Date;
  Sitcie?: string;
  Retcie?: string;
  Dsitcie?: Date;
  Numcie?: string;
  Debeffet?: Date;
  Fineffet?: Date;
  Debit?: Date;
  Rcm?: number;
  Indice?: number;
  Coeff?: string;
  Soldedu?: number;
  Soldedu1?: string;
  Totquit?: number;
  Totquit1?: string;
  Ptotale?: number;
  Ptotale1?: string;
  Pnette?: number;
  Pnette1?: string;
  Ppure?: number;
  Ppure1?: string;
  Catnat?: number;
  Catnat1?: string;
  Ristec?: number;
  Ristec1?: string;
  Frcie?: number;
  Frcie1?: string;
  Comm?: number;
  Comm1?: string;
  Commges?: number;
  Commges1?: string;
  Taxe?: number;
  Taxe1?: string;
  Taxatt?: number;
  Taxatt1?: string;
  Frgest?: number;
  Frgest1?: string;
  Netcie?: number;
  Netcie1?: string;
  Acompte?: number;
  Acompte1?: string;
  Hono?: number;
  Hono1?: string;
  CodeTva?: string;
  TauxTva?: number;
  Tvafr?: number;
  Tvafr1?: string;
  Frprel?: number;
  Frprel1?: string;
  Frcbt?: number;
  Frcbt1?: string;
  Memo?: string;
  Prorata?: number;
  Numtiers?: number;
  Prelevok?: boolean;
  Datenc?: Date;
  Commatt?: number;
  Commatt1?: string;
  Ecart?: number;
  Ecart1?: string;
  Histo?: string;
  Coeffenc?: number;
  Libelle?: string;
  Adhesion?: number;
  Tvaht?: number;
  Tvaht1?: string;
  Tvamnt?: number;
  Tvamnt1?: string;
  Nfacture?: string;
  Basetra?: number;
  Basetra1?: string;
  Basetrb?: number;
  Basetrb1?: string;
  Basetrc?: number;
  Basetrc1?: string;
  Txtra?: number;
  Txtrb?: number;
  Txtrc?: number;
  Txdna?: number;
  Mandat?: number;
  Dispatch?: boolean;
  Quitlie?: number;
  Echprin?: boolean;
  Ext?: string;
}
export enum QitNature { }
export enum QitGestion { }
export enum QitRole { }
export enum QitSitCie { }
export enum QitSitCli { }
export enum QitRetour { }
export enum Frais { }
