export interface Tier {
    numtiers: number;
    typtiers?: string;
    nattiers?: string;
    numdpp?: number;
    titre?: string;
    rsociale?: string;
    referenc?: string;
    connexe?: string;
    refext?: string;
    adr1?: string;
    adr2?: string;
    adr3?: string;
    codp?: string;
    ville?: string;
    codepays?: string;
    pays?: string;
    ntel?: string;
    nfax?: string;
    numemail?: string;
    memo?: string;
    ext?: string;
    images?: string;
    titnom?: string;
    gommette?: string;
    ole?: string;
    titrecou?: string;
    datdermo?: string; // ISO 8601 format date-time
    modifpar?: string;
    nbpercha?: number;
    const?: string;
    histo?: string;
    adrinsee?: boolean;
    adresse1?: string;
    adresse2?: string;
    adresse3?: string;
    grcok?: boolean;
    nonepur?: boolean;
    territory?: string;
    latitude?: number;
    longitude?: number;
  }
  
  export const TierTagdMap: Record<keyof Tier, string> = {
    "numtiers": "B_NUMTIERS",
    "typtiers": "B_TYPTIERS",
    "numdpp": "B_NUMDPP",
    "titre": "B_TITRE",
    "rsociale": "B_RSOCIALE",
    "referenc": "B_REFERENC",
    "connexe": "B_CONNEXE",
    "refext": "B_REFEXT",
    "adr1": "B_ADR1",
    "adr2": "B_ADR2",
    "adr3": "B_ADR3",
    "codp": "B_CODP",
    "ville": "B_VILLE",
    "codepays": "B_CODEPAYS",
    "pays": "B_PAYS",
    "ntel": "B_NTEL",
    "nfax": "B_NFAX",
    "numemail": "B_NUMEMAIL",
    "memo": "B_MEMO",
    "ext": "B_EXT",
    "images": "B_IMAGES",
    "gommette": "B_GOMMETTE",
    "ole": "B_OLE",
    "datdermo": "B_DATDERMO",
    "modifpar": "B_MODIFPAR",
    "nbpercha": "B_NBPERCHA",
    "histo": "B_HISTO",
    "adrinsee": "B_ADRINSEE",
    "grcok": "B_GRCOK",
    "nonepur": "B_NONEPUR",
    "territory": "B_TERRITORY",
    "latitude": "B_LATITUDE",
    "longitude": "B_LONGITUDE",
    nattiers: "B_nattiers",
    titnom: "B_titnom",
    titrecou: "B_titrecou",
    const: "B_const",
    adresse1: "B_adresse1",
    adresse2: "B_adresse2",
    adresse3: "B_adresse3"
  }