import { Component } from '@angular/core';
import { Produit } from '../../Model/produit.model';

@Component({
  selector: 'produits',
  imports: [],
  templateUrl: './produits.component.html',
  styleUrl: './produits.component.css'
})
export class ProduitsComponent {
 produits: Produit[] = [
  {
    codeprod: "AUTO_TPL",
    branche: "Automobile",
    libelle: "Responsabilité Civile Automobile",
    cieprin: "AXA",
    listeext: "Standard",
    pronopol: "OUI",
    pronoave: "NON",
    groupe: "AUTO",
    tartype: "Forfait",
    tardev: "MAD",
    tarcle: "A",
    tararro: null,
    taxatt: 15,
    taxatt1: "TVA",
    ftaxatt: "Inclus",
    sceretro: "NON",
    tauxatt: 0.2,
    modgarc: "Obligatoire",
    modgarr: "Optionnelle",
    tauxano: 0.05,
    formcomm: "Commission standard",
    extobli: "OUI",
    paniers: "Classique",
    nondispo: null,
    majcrm: "OUI",
    tarmaj: "Indexé",
    modegest: "Automatique",
    ctrlgar: "OUI",
    catalog: "V1",
    ole: "NON",
    typarro: "Aucun",
    fvahom: null
  },
  {
    codeprod: "AUTO_DMG",
    branche: "Automobile",
    libelle: "Dommages Tous Risques",
    cieprin: "Wafa Assurance",
    listeext: "Premium",
    pronopol: "NON",
    pronoave: "OUI",
    groupe: "AUTO",
    tartype: "Variable",
    tardev: "MAD",
    tarcle: "B",
    tararro: null,
    taxatt: 20,
    taxatt1: "TVA",
    ftaxatt: "Inclus",
    sceretro: "OUI",
    tauxatt: 0.3,
    modgarc: "Optionnelle",
    modgarr: "Optionnelle",
    tauxano: 0.07,
    formcomm: "Commission majorée",
    extobli: "NON",
    paniers: "Premium",
    nondispo: null,
    majcrm: "OUI",
    tarmaj: "Révisable",
    modegest: "Manuel",
    ctrlgar: "OUI",
    catalog: "V1",
    ole: "OUI",
    typarro: "Aucun",
    fvahom: null
  },
  {
    codeprod: "SANTE_BASE",
    branche: "Santé",
    libelle: "Assurance Santé de Base",
    cieprin: "Allianz",
    listeext: "Standard",
    pronopol: "OUI",
    pronoave: "OUI",
    groupe: "SANTE",
    tartype: "Forfait",
    tardev: "MAD",
    tarcle: "S",
    tararro: null,
    taxatt: 10,
    taxatt1: "TVA",
    ftaxatt: "Inclus",
    sceretro: "NON",
    tauxatt: 0.15,
    modgarc: "Obligatoire",
    modgarr: "Optionnelle",
    tauxano: 0.02,
    formcomm: "Commission standard",
    extobli: "NON",
    paniers: "Standard",
    nondispo: null,
    majcrm: "OUI",
    tarmaj: "Révisable",
    modegest: "Automatique",
    ctrlgar: "NON",
    catalog: "V1",
    ole: "NON",
    typarro: "Aucun",
    fvahom: null
  },
  {
    codeprod: "HABITATION_MR",
    branche: "Habitation",
    libelle: "Multirisques Habitation",
    cieprin: "Saham Assurance",
    listeext: "Complet",
    pronopol: "NON",
    pronoave: "NON",
    groupe: "HABITATION",
    tartype: "Forfait",
    tardev: "MAD",
    tarcle: "H",
    tararro: null,
    taxatt: 12,
    taxatt1: "TVA",
    ftaxatt: "Inclus",
    sceretro: "NON",
    tauxatt: 0.1,
    modgarc: "Obligatoire",
    modgarr: "Optionnelle",
    tauxano: 0.04,
    formcomm: "Commission standard",
    extobli: "OUI",
    paniers: "Classique",
    nondispo: null,
    majcrm: "OUI",
    tarmaj: "Indexé",
    modegest: "Automatique",
    ctrlgar: "OUI",
    catalog: "V1",
    ole: "NON",
    typarro: "Aucun",
    fvahom: null
  },
  {
    codeprod: "RC_PRO",
    branche: "Responsabilité Civile",
    libelle: "Responsabilité Civile Professionnelle",
    cieprin: "AXA",
    listeext: "Pro",
    pronopol: "NON",
    pronoave: "OUI",
    groupe: "RC",
    tartype: "Variable",
    tardev: "MAD",
    tarcle: "RC",
    tararro: null,
    taxatt: 15,
    taxatt1: "TVA",
    ftaxatt: "Inclus",
    sceretro: "NON",
    tauxatt: 0.18,
    modgarc: "Obligatoire",
    modgarr: "Optionnelle",
    tauxano: 0.03,
    formcomm: "Commission majorée",
    extobli: "NON",
    paniers: "Professionnel",
    nondispo: null,
    majcrm: "NON",
    tarmaj: "Révisable",
    modegest: "Manuel",
    ctrlgar: "OUI",
    catalog: "V2",
    ole: "OUI",
    typarro: "Aucun",
    fvahom: null
  },
  {
    codeprod: "VOYAGE_INT",
    branche: "Voyage",
    libelle: "Assurance Voyage Internationale",
    cieprin: "AXA",
    listeext: "Standard",
    pronopol: "OUI",
    pronoave: "NON",
    groupe: "VOYAGE",
    tartype: "Forfait",
    tardev: "MAD",
    tarcle: "V",
    tararro: null,
    taxatt: 12,
    taxatt1: "TVA",
    ftaxatt: "Inclus",
    sceretro: "NON",
    tauxatt: 0.1,
    modgarc: "Optionnelle",
    modgarr: "Optionnelle",
    tauxano: 0.03,
    formcomm: "Commission standard",
    extobli: "NON",
    paniers: "Voyage",
    nondispo: null,
    majcrm: "OUI",
    tarmaj: "Révisable",
    modegest: "Automatique",
    ctrlgar: "NON",
    catalog: "V1",
    ole: "NON",
    typarro: "Aucun",
    fvahom: null
  },
  {
    codeprod: "ACCIDENT_PERSO",
    branche: "Accidents",
    libelle: "Accidents Corporels",
    cieprin: "Saham Assurance",
    listeext: "Standard",
    pronopol: "NON",
    pronoave: "OUI",
    groupe: "ACCIDENT",
    tartype: "Forfait",
    tardev: "MAD",
    tarcle: "A",
    tararro: null,
    taxatt: 8,
    taxatt1: "TVA",
    ftaxatt: "Inclus",
    sceretro: "OUI",
    tauxatt: 0.05,
    modgarc: "Obligatoire",
    modgarr: "Optionnelle",
    tauxano: 0.01,
    formcomm: "Commission standard",
    extobli: "NON",
    paniers: "Classique",
    nondispo: null,
    majcrm: "OUI",
    tarmaj: "Indexé",
    modegest: "Manuel",
    ctrlgar: "NON",
    catalog: "V1",
    ole: "NON",
    typarro: "Aucun",
    fvahom: null
  },
  // Tu peux dupliquer en changeant juste les valeurs pour en ajouter encore plus
];

}
