import { Component } from '@angular/core';
import { QborModel } from '../../../Model/qbor.model';
import { MatIconModule } from '@angular/material/icon';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'list',
  imports: [MatIconModule, RouterLink],
  templateUrl: './list.component.html',
  styleUrl: './list.component.css'
})
export class ListBordereauxComponent {
 MOCK_BORDEREAUX: QborModel[] = [
  {
    numero: 1001,
    modele: true,
    nom: 'Modèle Auto',
    entite: 1,
    mois: 7,
    annee: 2025,
    cie: 101,
    nature: 'C', // Comptant
    confie: false,
    gestion: 'AUTO',
    bloque: false,
    affecte: false,
    debit: new Date('2025-07-01'),
    emission: 1,
    encaiss: 1,
    sequence: 'A202507001',
    fraiscab: 'STANDARD',
    date_enr: new Date(),
    nbquitt: 5,
    totpte: 12000,
    totpte1: 'DJF',
    totcomm: 1500,
    totcomm1: 'DJF',
    totpn: 10500,
    totpn1: 'DJF',
    modegest: 'AUTO',
  },
  {
    numero: 1002,
    nom: 'Modèle Santé',
    entite: 2,
    mois: 7,
    annee: 2025,
    cie: 202,
    nature: 'R',
    confie: true,
    gestion: 'SANTE',
    bloque: false,
    affecte: true,
    debit: new Date('2025-07-01'),
    emission: 2,
    encaiss: 2,
    sequence: 'S202507002',
    fraiscab: 'PERCENT',
    date_enr: new Date(),
    nbquitt: 12,
    totpte: 25000,
    totpte1: 'DJF',
    totcomm: 5000,
    totcomm1: 'DJF',
    totpn: 20000,
    totpn1: 'DJF',
    modegest: 'SANTE',
  },
  // 8 autres objets générés à titre d'exemple :
  ...Array.from({ length: 8 }, (_, i) => ({
    numero: 1003 + i,
    nom: `Bordereau ${i + 3}`,
    entite: i + 1,
    mois: 7,
    annee: 2025,
    cie: 300 + i,
    nature: i % 2 === 0 ? 'C' : 'R',
    confie: i % 3 === 0,
    gestion: 'GEN',
    bloque: false,
    affecte: i % 2 === 0,
    debit: new Date(`2025-07-${i + 3}`),
    emission: 1,
    encaiss: 2,
    sequence: `SEQ20250700${i + 3}`,
    fraiscab: 'STANDARD',
    date_enr: new Date(),
    nbquitt: 5 + i,
    totpte: 10000 + i * 500,
    totpte1: 'DJF',
    totcomm: 1500 + i * 200,
    totcomm1: 'DJF',
    totpn: 8500 + i * 300,
    totpn1: 'DJF',
    modegest: 'GEN',
  })),
];
}
